# Generated by Django 4.2.11 on 2024-04-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamingapp', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
    ]
