# Generated by Django 4.2.11 on 2024-04-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videostreamingapp', '0003_remove_video_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videostreamingapp.customuser'),
            preserve_default=False,
        ),
    ]
